POST http://localhost:4000/api/login/
Content-Type: application/json

{
  "username": "sarah",
  "password": "sarah"
}

###

POST http://localhost:4000/api/login/
Content-Type: application/json

{
  "username": "sarah",
  "password": "sarah2"
}