GET http://localhost:4000/api/books

###

POST http://localhost:4000/api/books
Content-Type: application/json

{
    "title": "Harry Potter",
    "author": "JK R.",
    "genre": "fiction",
    "available": true
}

###

POST http://localhost:4000/api/books
Content-Type: application/json

{
    "title": "Harry Potter",
    "author": "l",
    "genre": "",
    "available": true
}

###

DELETE http://localhost:4000/api/books/60bf74039de0b554b477afed

###

PUT http://localhost:4000/api/books/60bf74879fdb373f90cc556d
Content-Type: application/json

{
    "title": "Super Junior",
    "author": "Kyu Hyun",
    "genre": "non-fiction"
}

