GET http://localhost:4000/api/books

###

POST http://localhost:4000/api/books
Content-Type: application/json

{
    "title": "Harry Potter",
    "author": "JK R.",
    "genre": "fiction",
    "available": true
}

###

POST http://localhost:4000/api/books
Content-Type: application/json

{
    "title": "Harry Potter",
    "author": "l",
    "genre": "",
    "available": true
}

###

DELETE http://localhost:4000/api/books/60c5b14baac9b9f1fb1e24f4


