GET http://localhost:4000/api/users/

###

POST http://localhost:4000/api/users/
Content-Type: application/json

{
    "username": "student",
    "name": "Stu Dent",
    "password": "student",
    "userType": "student"
}

###

POST http://localhost:4000/api/users/
Content-Type: application/json

{
    "username": "",
    "name": "Sarah",
    "password": "sarah"
}

###

POST http://localhost:4000/api/users/
Content-Type: application/json

{
    "username": "sarah2",
    "name": "Sarah",
    "password": ""
}

